steps:
- id: 'branch name'
  name: 'alpine'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
    echo "***************************************************************"
    echo "PROJECT_ID:   $PROJECT_ID"
    echo "BUILD_ID:     $BUILD_ID"
    echo "CONFIG_PATH:  $TRIGGER_BUILD_CONFIG_PATH"
    echo "REPO_NAME:    $REPO_NAME"
    echo "BRANCH_NAME:  $BRANCH_NAME"
    echo "TAG_NAME:     $TAG_NAME"
    echo "TRIGGER_NAME: $TRIGGER_NAME"
    echo "***************************************************************"

- id: 'tf init'
  name: 'hashicorp/terraform:1.0.0'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
    echo "[init] dev_infra_tf"

- id: 'tf plan'
  name: 'hashicorp/terraform:1.0.0'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
    echo "[plan] dev_infra_tf"

- id: 'tf apply'
  name: 'hashicorp/terraform:1.0.0'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
    echo "[apply] dev_infra_tf"
